"""create new column column nameg mail in todos_work  table

Revision ID: 3487f94c9b7c
Revises: 8d228e997206
Create Date: 2025-03-27 23:46:57.798282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3487f94c9b7c'
down_revision: Union[str, None] = '8d228e997206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos_work', sa.Column('gmail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos_work', 'gmail')
    # ### end Alembic commands ###
